esphome:
  name: kamin
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: ""
  password: ""

# Enable logging
logger:

# Enable Home Assistant API

api:
  services:
    - service: control_servo
      variables:
        level: float
      then:
        - servo.write:
            id: kamin_servo
            level: !lambda 'return level / 100.0;'

ota:


i2c:
  sda: D5
  scl: D6
  scan: True
  
spi:
  miso_pin: GPIO15
  clk_pin: GPIO1
  
switch:
  - platform: gpio
    name: "Kamin Relay"
    pin: 
      number: GPIO13
      inverted: true

sensor:
  - platform: max6675
    name: "Kamin Core Temp"
    cs_pin: GPIO3
    update_interval: 60s
  - platform: bme280
    temperature:
      name: "Kamin Temperatur"
      oversampling: 16x
      id: temp
      filters:
       - offset: -4.5
    pressure:
      name: "Kamin Pressure"
    humidity:
      name: "Kamin Humidity"
    address: 0x76
    update_interval: 20s
    

output:
  - platform: esp8266_pwm
    pin: D1
    frequency: 50 hz
    id: servo_kamin
  
    
servo:
  - id: kamin_servo
    output: servo_kamin
